print("This is teja using python to commit")
print("you are in saibranch")
print('I can edit it')
print('hello ppl, its uthara :D')
print("i can edit this")
print("Why is manasa not able to edit it")
